CREATE TABLE dados(
   id        INTEGER  NOT NULL PRIMARY KEY 
  ,nome      VARCHAR(25) NOT NULL
  ,categoria VARCHAR(13) NOT NULL
  ,descricao VARCHAR(313) NOT NULL
  ,imagem    VARCHAR(24)
);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (1,'Slender','Terror','Slender: The Seven Missing Pages é um jogo de terror, onde o objetivo é procurar pelas sete páginas para sobreviver ao ''homem'' de terno sem rosto.','imagens/slender.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (2,'Resident Evil','Terror','Resident Evil: É um jogo onde seu objetivo é tentar sobreviver neste lugar repleto de criaturas e seres humanos infectados.','imagens/residentevil.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (3,'Silent Hill','Terror','Silent Hill: É um jogo onde o personagem vive dentro de uma cidade que está dentro da sua cabeça com todos os seu medos refletidos em monstros, onde você terá de enfrentá los, e tentar sobreviver.','imagens/silenthill.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (4,'FnaF','Terror','Cercado por animatronicos assombrados, você é um guarda noturno cujo único dever e desejo é sair vivo dessa pizzaria fantasmagórica.','imagens/fnaf.png');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (5,'Friday the 13th: The Game','Terror','Friday the 13th: É um jogo de sobrevivência, onde você deve fugir dos assassinos a solta que estão indo atrás de você.','imagens/friday.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (6,'Emily wants to Play','Terror','Você é um entregador de pizza apressado para terminar seu serviço. Na última casa a ser entregue, ninguém atende à porta, então você, resitando, entra na casa e logo se arrepende','imagens/emily.png');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (7,'Sara is Missing','Terror','Você apanha um celular do chão e logo, através da assistente virtual do mesmo, descobre que a dona está desaparecida. Usando seus contatos, mensagens, e-mails, e imagens, você faz o possível para saber onde a menina foi parar, descobre-se que não foi apenas um desaparecimento.','imagens/sara.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (8,'P.T.','Terror','PT, praticamente era uma Demo onde você deveria percorrer a casa em loop, fugindo da criatura que assombra a casa.','imagens/pt.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (9,'Amnesia','Terror','Amnesia, jogo onde você deve permanecer consciente e sano para sobreviver e fugir das criaturas desse lugar','imagens/amnesia.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (10,'Shadow of the colossus','Ação-Aventura','Em shadow of the colossus você estará exilado em terras amaldiçoadas, você terá que derrotar 16 colossus em busca de reviver a sua amada.','imagens/shadow.png');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (11,'Assassin''s Creed','Ação-Aventura','Jogo onde você faz parte da ordem dos assassinos que desejam a paz através do livre arbítrio e deve derrotar os Templários.','imagens/ac.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (12,'GTA V','Ação-Aventura','Neste jogo totalmente freeroam, você pode realizar várias coisas, desde um assalto de caminhão, até perseguição de velhinhas na rua.','imagens/gtaa.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (13,'Pay Day 2','Ação-Aventura','Junto de 3 ou mais jogadores, vocês terão que bolar uma estratégia para roubar um banco.','imagens/payday2.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (14,'The Biding of Isaac','Ação-Aventura','Fugindo de sua mãe ao tentar te matar, Isaac foge para o porão, enfrentando lá criaturas.','imagens/isac.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (15,'The Legend of Zelda','Ação-Aventura','Você jogará com o personagem e herói Link cuja missão é proteger o reino de Hyrule e a Triforce, a relíquia deixada pelas Deusas criadoras do mundo.','imagens/zelda.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (16,'World of Tanks','Ação-Aventura','Jogo multiplayer onde você pode possuir tanque de guerra de várias nações, e jogar em diversos modos de jogo, destruindo os tanques inimigos.','imagens/wot.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (17,'Tomb Raider','Ação-Aventura','Jogando com a personagem Lara Croft, uma jovem mulher que é sobrevivente experiente. Armada apenas com os seus instintos e a capacidade de ir além dos limites da resistência humana, Lara precisa lutar para desvendar a história sombria de uma ilha esquecida para fugir das suas garras.','imagens/tomb-raider.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (18,'God of War','Ação-Aventura','Kratos, um guerreiro espartano enganado para matar sua esposa e filha por seu antigo mestre, o deus da guerra Ares. Revelado ser um semideus e filho de Zeus, o rei dos deuses do Olimpo, que trai Kratos. O espartano em seguida busca vingança contra os deuses para suas maquinações.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (19,'Doom','Ação-Aventura','O jogador recebe o papel de um fuzileiro espacial, que foi deportado para Marte e subitamente, algo dá errado e criaturas aparentemente vindas do inferno começam a surgir das áreas de teletransporte.','imagens/doom.jpeg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (20,'Dark Souls','RPG','Neste mundo tomado pelo Abismo, cheios de criatura amaldiçoadas, você terá que decidir o destino de seu mundo nas trevas ou na luz.','imagens/dark-souls.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (21,'Bloodborne','RPG','Nesta terra Amaldiçoada pelo sangue ruim, e criaturas grotescas, você deve enfrentar, para achar a cura.','imagens/bloodborne.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (22,'Undertale','RPG','Você deve escolher um caminho. Matar os monstros para sobreviver, ou arriscar a própria vida em nome deles?',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (23,'StarBound','RPG','Com o objetivo de salvar o mundo, você é mandado em várias missões para resgatar diversas tribos/povos de muitos mundos.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (24,'The Sims 4','RPG','Em um mundo totalmente manipulável, você pode construir sua própria família, personalizar seus sims, e conseguir objetivos especiais desbloqueando capítulos para seus sims fazerem',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (25,'League of Legends','RPG','os jogadores assumem o papel de "invocadores", controlando campeões com habilidades únicas e que lutam com seu time contra outros invocadores. No modo mais popular do jogo, o objetivo de cada time é destruir o nexus da equipe adversária, uma construção localizada na base e protegida por outras estruturas.','imagens/lol.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (26,'The Witcher 3','RPG','Seu protagonista, deve enfrentar  o macabro exército de cavaleiros que deixam somente sangue e ruína por onde passa, o jogador terá de enfrentar diversos perigos usando espadas e magia num mundo em crise.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (27,'Tera','RPG','Seu protagonista, deve enfrentar  o macabro exército de cavaleiros que deixam somente sangue e ruína por onde passa, o jogador terá de enfrentar diversos perigos usando espadas e magia num mundo em crise.','imagens/tera.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (28,'Pokemon:Platina','RPG','O jogador controla um personagem criança em sua aventura pela região de Sinnoh; que começa ao receber um dos três pokémons iniciais - Chimchar, Turtwig ou Piplup.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (29,'World of Warcraft','RPG','Uma nova era de guerras se inicia, e os heróis de Azeroth terão que partir numa jornada para recrutar novos aliados, disputar os recursos mais valiosos do mundo para dominar o conflito e combater em diversas linhas de frente para determinar se será a Horda ou a Aliança quem conduzirá o futuro incerto de Azeroth.','imagens/wow.jpg');
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (30,'Final Fantasy','RPG','O mundo de Final Fantasy VII é chamado dentro de jogo de simplesmente "o Planeta", porém foi retroativamente nomeado Gaia e é formado por três massas continentais principais.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (31,'Earthbound','RPG','Em EarthBound você não vai encontrar espadas, dragões e nada parecido. Mas vai se deparar com hippies alucinados, criaturas espaciais, durante a aventura é melhor estar pronto para referências aos costumes suburbanos e ideias que lá no fundo toda pessoa tem mas parece ser absurda, como a do vizinho malvado.',NULL);
INSERT INTO dados(id,nome,categoria,descricao,imagem) VALUES (32,'Fallout 4','RPG','Você está em um mundo pós-apocalíptico, onde agora está cheio de criaturas mutantes e de pessoas mal intencionadas e agora você de sobreviver a tudo isso.','imagens/fallout.jpeg');
